// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALiaSaxo0mViOY9Ia5N-liGgb_56rSu3c',
    appId: '1:468584920205:web:3696f1422897fb88759ec4',
    messagingSenderId: '468584920205',
    projectId: 'saveit-by-vertex',
    authDomain: 'saveit-by-vertex.firebaseapp.com',
    storageBucket: 'saveit-by-vertex.firebasestorage.app',
    measurementId: 'G-93TB9G8J4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjKCqu8ICh2m_H8ncsyELoU5XscTKEhtQ',
    appId: '1:468584920205:android:c04286b2e90232e9759ec4',
    messagingSenderId: '468584920205',
    projectId: 'saveit-by-vertex',
    storageBucket: 'saveit-by-vertex.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKcMgUE7NCWmXckT-fxCFUJ1U4K-GPBVU',
    appId: '1:468584920205:ios:5b82f1353306d258759ec4',
    messagingSenderId: '468584920205',
    projectId: 'saveit-by-vertex',
    storageBucket: 'saveit-by-vertex.firebasestorage.app',
    androidClientId: '468584920205-lj9jkkp1tt3tf8rgis6n5374oshdr5oi.apps.googleusercontent.com',
    iosClientId: '468584920205-as9imgpck8q1okfc7rjr79fugpedi723.apps.googleusercontent.com',
    iosBundleId: 'com.example.saveltApp',
  );
}
